"use client"

// Account form dialog — add a company, or edit any account. `initial` present =
// edit mode (prefilled). Companies and people are still ONE list (SCOPE ch.03),
// told apart by Type, so this is still the one form for both — a person opened
// from their own screen is edited here too.
//
// THE TYPE SELECTOR IS GONE, and that is the owner's ruling of 18 Aug 2026,
// which reverses his own of the day before: "all new accounts will always be
// companies… we are no longer going to show the dropdown at the form creation
// or form edit for the account level." The COLUMN stays (`accounts.account_type`,
// a live CHECK constraint, and the thing that decides which of the two screens
// an account gets) — only the question goes.
//
// SO THE FORM NO LONGER ASKS, AND THEREFORE NO LONGER DECIDES. `accountType` is
// still in the values and still sent, because a form that stops asking while
// still sending yesterday's answer is how a field gets zeroed on every edit
// (CHECKLIST 3.13). It is PINNED instead: creating from here always makes a
// company, editing carries the record's own value straight through untouched, so
// a person edited from their contact screen is still a person afterwards.
//
// A PERSON IS BORN ON A COMPANY'S CONTACTS TAB now, not here — account-detail's
// `createContact`, which fills the type in as code rather than offering it as a
// choice. That tab is the reason this selector could go at all: it was the only
// way to create a person in the whole app.
//
// THE REFERENCE IS NOT ON THIS FORM. "The reference is generated by the system,
// not staff. Therefore no-one would type." The door mints it from the name (BERG
// for Bergman S.A., BERG2 when that is taken) and the partial unique index on
// `accounts(code)` is what decides a clash — so there is no field here, and no
// conflict dialog to design, because nobody is ever standing in front of one.
//
// THE ADDRESS IS FOUR FIELDS. A country typed free is a country spelled five
// ways, so it is picked from the team's own Country group; the industry is
// picked the same way. Both lists come from the dropdown values screen, fetched
// here rather than passed in, because this dialog is mounted by the deep-link
// host and its call sites hand it only the two option lists they already hold.
//
// THE PARENT PICKER IS GONE TOO, and it is the same ruling one field along
// (18 Aug 2026): "each new account created will be its own thing. It will have
// no parent because it's literally a brand new company." A company an agency
// takes on is a company, not a subsidiary of one already on the books, so the
// form stopped asking a question whose honest answer was always "none" — and it
// stopped asking it on the EDIT half as well, because a control nobody wanted on
// the way in is not one they wanted on the way back.
//
// THE COLUMN, THE DOOR AND THE LINE ON THE RECORD ALL STAY. `parent_account_id`
// is what puts a contact under her company (account-detail's `createContact`
// writes it in code), the account screen still reads "Parent account · Bergman
// S.A." on its Overview, and `/api/tenancy/accounts/parent` is still a door.
// What went from THIS FORM is the control, and only from this form: asking a
// brand new company who its parent is is a question with one honest answer, and
// asking it again on the way back out is the same question twice.
//
// A PERSON DOES GET ASKED, ON HER OWN RECORD (19 Aug 2026 —
// contact-detail's `moveToCompany`). Taking the picker off the edit half left a
// contact who changes employer with no screen that could move her, and the note
// the removing lane wrote said where the answer would have to go if anybody
// asked: on the CONTACT, not back on a company's form. That is where it is.
//
// Unlike `accountType`, the field is not carried through either: `updateAccount`
// never reads it (a move is its own door — see `setAccountParent`'s note in
// workers/tenancy/src/lib/accounts.ts), so a form that stopped sending it cannot
// zero anything. The two halves of CHECKLIST 3.13 are "does the door read it?"
// and "does the form still answer it?" — here the first is no, so the second is
// moot.
//
// Shared FormShell layout (Law R4) + a per-session draft (Law R7 · CACHING.md §11).

import * as React from "react"

import { Avatar, AvatarFallback, AvatarImage } from "@shared/ui/components/avatar/avatar"
import {
  DialogDescription,
  DialogTitle,
} from "@shared/ui/components/dialog/dialog"
import { Field } from "@shared/web/field"
import { FileUpload } from "@shared/ui/components/file-upload/file-upload"
import { Image } from "@shared/ui/components/image/image"
import { Input } from "@shared/ui/components/input/input"
import { Notes } from "@shared/web/notes-editor/notes-editor"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@shared/ui/components/select/select"
import { toast } from "@shared/ui/components/sonner/sonner"
import { defaultFieldConfig } from "@shared/web/screen-engine/config"

import { ApiFailure, tenancy } from "@/lib/api"
import { fileToDataUrl } from "@/lib/image"
import { safeSrc } from "@shared/web/rich-text"
import { LANGUAGES } from "@shared/i18n"
import { FormShellDialog, fieldSpacing } from "@shared/web/form-shell"
import { useCached } from "@shared/web/store"
import { useFormDraft } from "@shared/web/use-form-draft"
import { useT } from "@shared/web/language"

const nameField = { ...defaultFieldConfig, label: "Name", required: true }
const emailField = { ...defaultFieldConfig, label: "Email", required: false }
const phoneField = { ...defaultFieldConfig, label: "Phone", required: false }
const streetField = { ...defaultFieldConfig, label: "Street", required: false }
const postalField = { ...defaultFieldConfig, label: "Postal code", required: false }
const cityField = { ...defaultFieldConfig, label: "City", required: false }
const countryField = { ...defaultFieldConfig, label: "Country", required: false }
const industryField = { ...defaultFieldConfig, label: "Industry", required: false }
const aboutField = { ...defaultFieldConfig, label: "About", required: false }
const languageField = { ...defaultFieldConfig, label: "Language", required: false }
const logoField = { ...defaultFieldConfig, label: "Logo", required: false }
const coverField = { ...defaultFieldConfig, label: "Cover image", required: false }

// Radix Select can't hold an empty value, so "not chosen" is a sentinel. One
// constant for all four pickers — four spellings of the same idea is how one of
// them ends up storing the literal string.
const NONE = "__none__"

/** What the form prefills from and submits — the editable surface of an account.
 * `code` is absent on purpose: the system mints it (see the header). */
export type AccountFormValues = {
  /** Carried, never asked — see the header. On an edit this is the record's own
   * value coming in and going back out unchanged; on a create it is pinned to
   * `entity`. It is here at all because the door needs it on a create and
   * because the Industry field is only a company's question. */
  accountType: "entity" | "individual"
  name: string
  email: string
  phone: string
  street: string
  postalCode: string
  city: string
  country: string
  industry: string
  /** rich text (HTML), authored in the library Notes editor */
  about: string
  /** a data URL from the picker, or a URL already on the record */
  logoUrl: string
  coverUrl: string
  /** the language this account is written to (a BCP-47 tag, or "" for ours) */
  locale: string
}

const EMPTY: AccountFormValues = {
  accountType: "entity",
  name: "",
  email: "",
  phone: "",
  street: "",
  postalCode: "",
  city: "",
  country: "",
  industry: "",
  about: "",
  logoUrl: "",
  coverUrl: "",
  locale: "",
}

/** The first letters of a name, for the logo placeholder. */
function letterMark(name: string): string {
  return (name.trim()[0] ?? "?").toUpperCase()
}

export function AccountFormDialog({
  open,
  onOpenChange,
  initial,
  onSubmit,
  draftKey,
}: {
  open: boolean
  onOpenChange: (open: boolean) => void
  /** present = edit mode (prefilled); absent = create mode */
  initial?: AccountFormValues | null
  onSubmit: (values: AccountFormValues) => Promise<void>
  /** stable id for per-session draft persistence; omit to disable. */
  draftKey?: string
}) {
  const t = useT()
  const isEdit = !!initial
  const [values, setValues, clearDraft] = useFormDraft(draftKey, initial ?? EMPTY, open)
  const [busy, setBusy] = React.useState(false)

  // The team's own vocabulary for the two picked fields. Cache-first and shared
  // with the Dropdown values screen, so opening this form usually costs nothing
  // — and a team that adds "Logistics" over there sees it here without a deploy.
  const vocabularyQ = useCached(open ? "selectable:all" : null, () =>
    tenancy.selectable().then((r) => r.values)
  )
  const group = (type: string) =>
    (vocabularyQ.data ?? [])
      .filter((v) => v.type === type && v.active)
      .map((v) => ({ value: v.value, label: v.value }))
  const countries = group("Country")
  const industries = group("Industry")

  /** A picked image becomes a data URL on the record. Same seam the team logo
   * uses (lib/image downsizes before it ever reaches a body). */
  const pickImage = (field: "logoUrl" | "coverUrl") => async (files: File[]) => {
    if (!files[0]) return
    try {
      set({ [field]: await fileToDataUrl(files[0]) } as Partial<AccountFormValues>)
    } catch {
      toast.error(t("Couldn't read that image. Try another one."))
    }
  }

  // THE TYPE, DECIDED HERE RATHER THAN ANSWERED ON THE FORM. Creating from this
  // form always makes a company; an edit hands the record's own value back
  // untouched, which is what keeps a person a person.
  //
  // PINNED, not merely defaulted. A draft saved before the selector went is still
  // sitting in this browser's sessionStorage (`account:new:<teamId>`) and
  // `useFormDraft` would restore it — the answer to a question that is no longer
  // on screen, deciding a record nobody can see it decide.
  const accountType: AccountFormValues["accountType"] = isEdit ? values.accountType : "entity"

  async function submit(e: React.FormEvent) {
    e.preventDefault()
    if (!values.name.trim()) return
    setBusy(true)
    try {
      await onSubmit({ ...values, accountType })
      clearDraft()
      onOpenChange(false)
    } catch (err) {
      // The server's own sentence wins — it's the one that knows WHY (a duplicate
      // reference, a move that would put the account inside itself).
      toast.error(err instanceof ApiFailure ? err.message : t("Couldn't save the account."))
    } finally {
      setBusy(false)
    }
  }

  const set = (patch: Partial<AccountFormValues>) => setValues((v) => ({ ...v, ...patch }))

  /** A pick-from-the-team's-own-words field. Empty is always reachable, because
   * "we haven't asked them yet" is a real answer and a required dropdown would
   * make somebody guess. */
  const picker = (
    id: string,
    config: typeof countryField,
    value: string,
    options: { value: string; label: string }[],
    onPick: (v: string) => void,
    placeholder: string
  ) => (
    <Field config={config} htmlFor={id} className={fieldSpacing}>
      <Select value={value || NONE} onValueChange={(v) => onPick(v === NONE ? "" : v)} disabled={busy}>
        <SelectTrigger id={id}>
          <SelectValue placeholder={placeholder} />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value={NONE}>{placeholder}</SelectItem>
          {options.map((o) => (
            <SelectItem key={o.value} value={o.value}>
              {o.label}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </Field>
  )

  const isCompany = accountType === "entity"
  // A PREVIEW IS EITHER THE FILE JUST PICKED (a data URL, this session, in this
  // browser) OR THE STORED PATH (ordinary text a machine caller can write). The
  // second one goes through the URL boundary; the first cannot, because `safeSrc`
  // refuses `data:` on purpose — so it is named for what it is instead.
  const preview = (value: string) => (value.startsWith("data:") ? value : safeSrc(value))
  const logoPreview = preview(values.logoUrl)
  const coverPreview = preview(values.coverUrl)

  // THE TITLE AND THE SUBTITLE GO THROUGH `t` ON BOTH BRANCHES. A sentence
  // inside a ternary is a JSX EXPRESSION, not JSX text, so the catalogue's
  // extractor walks straight past it (R28 · scripts/lib/i18n-source.mjs) and it
  // would ship in English to somebody who chose German. The `t` call is the one
  // position that puts it back in reach. The create half is new copy here; the
  // edit half is wrapped beside it because a half-adopted pair is how the next
  // reader concludes the question was already settled.
  return (
    <FormShellDialog
      open={open}
      onOpenChange={onOpenChange}
      busy={busy}
      onSubmit={submit}
      title={
        <DialogTitle>{isEdit ? t("Edit this account") : t("Add an account")}</DialogTitle>
      }
      subtitle={
        <DialogDescription>
          {isEdit
            ? t("Update the details you hold for them.")
            : t("A company you work with. Everyone there goes on its Contacts tab.")}
        </DialogDescription>
      }
      submit={{
        busy: busy,
        disabled: !values.name.trim(),
      }}
    >
      {/* No Type field. The header says why, and the source assertion in
          web/test/accounts-are-companies.test.tsx holds it to it — a control
          nobody can see is a control nobody would notice coming back. */}
      <Field config={nameField} htmlFor="account-name" className={fieldSpacing}>
        <Input
          id="account-name"
          value={values.name}
          onChange={(e) => set({ name: e.target.value })}
          placeholder={t("Bergman S.A.")}
          disabled={busy}
          autoFocus
        />
      </Field>

      <Field config={emailField} htmlFor="account-email" className={fieldSpacing}>
        <Input
          id="account-email"
          type="email"
          value={values.email}
          onChange={(e) => set({ email: e.target.value })}
          placeholder="hola@bergman.example"
          disabled={busy}
        />
      </Field>

      <Field config={phoneField} htmlFor="account-phone" className={fieldSpacing}>
        <Input
          id="account-phone"
          value={values.phone}
          onChange={(e) => set({ phone: e.target.value })}
          placeholder="+34 600 000 000"
          disabled={busy}
        />
      </Field>

      {/* The postal address, in the four pieces a postal address has. */}
      <Field config={streetField} htmlFor="account-street" className={fieldSpacing}>
        <Input
          id="account-street"
          value={values.street}
          onChange={(e) => set({ street: e.target.value })}
          placeholder={t("Calle Mayor 1")}
          disabled={busy}
        />
      </Field>

      <Field config={postalField} htmlFor="account-postal" className={fieldSpacing}>
        <Input
          id="account-postal"
          value={values.postalCode}
          onChange={(e) => set({ postalCode: e.target.value })}
          placeholder="28013"
          disabled={busy}
        />
      </Field>

      <Field config={cityField} htmlFor="account-city" className={fieldSpacing}>
        <Input
          id="account-city"
          value={values.city}
          onChange={(e) => set({ city: e.target.value })}
          placeholder={t("Madrid")}
          disabled={busy}
        />
      </Field>

      {picker(
        "account-country",
        countryField,
        values.country,
        countries,
        (v) => set({ country: v }),
        t("Not said")
      )}

      {/* A person does not have an industry — the company they work at does. */}
      {isCompany &&
        picker(
          "account-industry",
          industryField,
          values.industry,
          industries,
          (v) => set({ industry: v }),
          t("Not said")
        )}

      {picker(
        "account-language",
        languageField,
        values.locale,
        LANGUAGES.map((l) => ({ value: l.code, label: l.english })),
        (v) => set({ locale: v }),
        t("Ours")
      )}

      <Field config={aboutField} htmlFor="account-about" className={fieldSpacing}>
        <Notes
          key={open ? "open" : "shut"}
          defaultValue={values.about}
          onChange={(html) => set({ about: html })}
          placeholder={t("What they do, who they are, anything worth knowing.")}
          className="min-h-32"
        />
      </Field>

      {/* HIDDEN UNTIL THERE IS A REAL PICTURE — the same fix as the app form's
          logo field, and the same reason: on a brand-new account `values.name`
          is still empty, so `letterMark` had nothing to fall back to but "?",
          drawing a placeholder that stood for nothing rather than for the
          record. "hide when empty, show when populated," not removed
          outright — the preview still confirms the file just picked before it
          uploads. */}
      <Field config={logoField} htmlFor="account-logo" className={fieldSpacing}>
        <div className="flex items-center gap-2">
          {logoPreview && (
            <Avatar className="size-12">
              <AvatarImage src={logoPreview} alt={t("Logo")} />
              <AvatarFallback>{letterMark(values.name)}</AvatarFallback>
            </Avatar>
          )}
          <FileUpload accept="image/*" multiple={false} onFilesSelected={pickImage("logoUrl")} />
        </div>
      </Field>

      <Field config={coverField} htmlFor="account-cover" className={fieldSpacing}>
        <div className="flex flex-col gap-2">
          {coverPreview && (
            /* The kit's media well, which is what this box already was by hand:
               the card radius, `object-cover`, the clip — and, new here, a
               register for a cover URL that will not load, where a bare <img>
               drew the browser's broken-picture glyph. `ratio={null}` because
               the height is the form's (80), not the well's own 16/9. */
            <Image src={coverPreview} alt={t("Cover image")} ratio={null} className="h-20 w-full" />
          )}
          <FileUpload accept="image/*" multiple={false} onFilesSelected={pickImage("coverUrl")} />
        </div>
      </Field>
    </FormShellDialog>
  )
}
