// THE ICON CHOICES FOR AN APP MODULE'S GALLERY CARD.
//
// Client's ruling, 17 Sep 2026, verbatim: "Inside an app, the tabs module: I
// want it to look exactly like the settings modules, this kind of gallery
// with the icons. When I add a module, I should be able to select an icon
// for it." Settings › Modules already draws every card from a FIXED
// vocabulary (`CONCEPT_ICON`, one icon per settings segment, chosen in code);
// an app module is a TEAM'S OWN row, so the icon is chosen on the form
// instead, and something has to say which choices are on offer.
//
// A REASONED, ROT-CHECKED ALLOW-LIST, the shape this codebase already uses
// for exactly this kind of thing (GLOSSARY_SYNONYMS, TOOLBAR_EXEMPT, …), and
// not the kit's whole 1,512-glyph catalogue: "app-relevant" curated by hand
// for what a software section commonly is (Settings, Documents, Billing, a
// database, a chat) rather than every glyph the kit happens to ship. Every
// name below is already drawn through the census both front doors compile
// against — `shared/web/screen-engine/icon-map.ts`, generated by `node
// scripts/icon-map.mjs` — because each one already sits in `CONCEPT_ICON`,
// `TAB_ICONS` or `KNOWLEDGE_KIND_ICON`; `web/test/module-icons.test.tsx` reads
// the generated map (through `iconComponent`) and fails the build if a name
// here ever stops resolving to a real glyph.
//
// A PLAIN STRING LIST ON PURPOSE, never a `shared/ui/foundations/icons`
// import: this file is compiled by workers/tenancy (the door's own R20 check
// validates `icon` against it, positionally) exactly as `shared/sprint-
// types.ts`'s own header explains for the identical reason — a worker's
// tsconfig excludes `shared/ui/` and `shared/web/` outright (no DOM, no
// React), so the allow-list has to be the kit's NAME for a glyph, resolved to
// real art only on the browser side, through `shared/web/screen-engine/
// icon.tsx`'s `Icon`.
//
// PHOSPHOR'S OWN NAMES, kebab-case (no alias layer, by direct client ruling,
// 2026-09-03 — see icon-names.ts's own header): go to phosphor.dev and read
// the name off the page.
export const MODULE_ICON_NAMES = [
  "app-window",
  "gear",
  "house",
  "squares-four",
  "stack",
  "package",
  "archive",
  "database",
  "file-text",
  "article",
  "clipboard-text",
  "note",
  "note-pencil",
  "envelope",
  "calendar",
  "chat-circle-text",
  "chat-teardrop",
  "puzzle-piece",
  "building",
  "buildings",
  "money",
  "network",
  "key",
  "shield-check",
  "bug",
  "scroll",
  "rocket-launch",
  "sparkle",
  "columns",
  "crosshair",
  "cube",
  "flow-arrow",
  "funnel",
  "question",
  "info",
  "list-bullets",
  "wrench",
  "target",
  "tray",
  "paperclip",
  "users",
  "user-circle",
  "palette",
  "chart-donut",
] as const

export type ModuleIconName = (typeof MODULE_ICON_NAMES)[number]

/** No icon chosen draws this — a plain section glyph, never a blank well
 * (the kit's `Icon` renders nothing at all for a name it cannot resolve, and
 * "nothing" is the wrong answer for the biggest mark on the card). */
export const DEFAULT_MODULE_ICON: ModuleIconName = "squares-four"
