#!/usr/bin/env node
/**
 * icon-map.mjs — write the explicit list of kit glyphs the app names as DATA.
 *
 *     node scripts/icon-map.mjs           regenerate
 *     node scripts/icon-map.mjs --check   verify only, exit 1 if stale
 *
 * WHY THIS EXISTS, and it is a bundle-size fact rather than a style choice.
 *
 * An icon named by data has to be looked up at runtime, and the obvious way to
 * do that is `import * as KitIcons` and index the namespace. That is what this
 * app did, and it was fine while the kit drew 96 glyphs: the whole namespace
 * was 56 KB. The kit draws 1,383 now. A namespace import that is INDEXED
 * DYNAMICALLY pins every export — the bundler cannot know which key you will
 * ask for — so the first build after the swap shipped a 1.0 MB chunk of icon
 * art to draw about eighty. The `/*#__PURE__*​/` annotations on the kit's side
 * do not help and cannot: the namespace object is genuinely used.
 *
 * So the lookup table is EXPLICIT. Named imports are statically analysable,
 * the bundler keeps the ~80 named here and drops the other ~1,300.
 *
 * It is generated rather than hand-kept because the vocabulary lives in four
 * places (TAB_ICONS, CONCEPT_ICON, KNOWLEDGE_KIND_ICON, and generic `icon:`
 * fields), and a hand-kept list would drift from them the first time somebody
 * adds a tab. web/test/icon-vocabulary.test.ts asserts the file is CURRENT,
 * the way `npm run lang:check` asserts the translation catalogue is.
 *
 * NO ALIAS TABLE any more (2026-09-03, the Phosphor swap): a name this app
 * stores IS the kit's own name, PascalCased, nothing translates it on the way
 * in. See shared/web/screen-engine/icon-names.ts.
 */

import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { sourceFiles } from "../shared/rules/source-scan.ts"

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const OUT = join(ROOT, "shared", "web", "screen-engine", "icon-map.ts")
const CHECK = process.argv.includes("--check")

const read = (p) => readFileSync(p, "utf8")

/** kebab → Pascal, the same transform icon-names.ts and the kit's generator use. */
const pascal = (k) =>
  k.split("-").map((p) => p.replace(/^([0-9]*)([a-z])/, (_, d, c) => d + c.toUpperCase())).join("")

/** Every name the app can hand to `iconComponent`, read where it is written.
 * The four positions, and nothing hand-listed. */
export function vocabulary() {
  const names = new Set()

  const table = (src, marker) => {
    const at = src.indexOf(marker)
    if (at === -1) return
    const body = src.slice(at, src.indexOf("\n}", at))
    for (const m of body.matchAll(/:\s*"([a-z][a-z0-9-]*)"/g)) names.add(m[1])
  }

  table(read(join(ROOT, "shared", "web", "screen-engine", "tabs-view.tsx")), "export const TAB_ICONS")
  table(read(join(ROOT, "web", "lib", "pages.ts")), "CONCEPT_ICON")
  table(read(join(ROOT, "web", "components", "deep-link", "shape.tsx")), "export const KNOWLEDGE_KIND_ICON")

  // THE MODULE ICON PICKER'S ALLOW-LIST (shared/module-icons.ts) — an ARRAY of
  // names a person chooses from, not a `key: "name"` table and not under any
  // root the walk below reads. Until 18 Sep 2026 two of its names were in the
  // map only because CONCEPT_ICON happened to use them too; the day
  // CONCEPT_ICON moved on, the picker's own test went red for a glyph the
  // map had silently dropped.
  const list = (src, marker) => {
    const at = src.indexOf(marker)
    if (at === -1) return
    const body = src.slice(at, src.indexOf("]", at))
    for (const m of body.matchAll(/"([a-z][a-z0-9-]*)"/g)) names.add(m[1])
  }
  list(read(join(ROOT, "shared", "module-icons.ts")), "export const MODULE_ICON_NAMES")

  for (const f of sourceFiles([join(ROOT, "web"), join(ROOT, "web-portal"), join(ROOT, "shared", "web")], {
    extensions: [".ts", ".tsx"],
    relativeTo: ROOT,
  })) {
    if (/(^|\/)(test|e2e)\//.test(f.rel)) continue
    for (const m of f.source.matchAll(/\bicon:\s*"([a-z][a-z0-9-]*)"/g)) names.add(m[1])
  }
  return names
}

/** Only names that resolve to real art. A name that does not is the census
 * test's failure to report, not this script's to paper over. */
const drawn = new Set(
  sourceFiles(join(ROOT, "shared", "ui", "foundations", "icons"), { extensions: [".svg"], recursive: false }).map((f) =>
    f.path.split("/").pop().slice(0, -4)
  )
)

const exports = [...new Set([...vocabulary()].map((n) => pascal(n)))].filter((e) => drawn.has(e)).sort()

const body = `// GENERATED by scripts/icon-map.mjs — do not hand-edit.
//
// The kit glyphs this app names as DATA, imported explicitly so a bundler can
// drop the other ${drawn.size - exports.length}. See the script's header for why a namespace
// import cannot work here: indexing one dynamically pins all ${drawn.size} exports, which
// shipped a 1.0 MB chunk on the first build after the Iconoir swap.
//
// Regenerate with \`node scripts/icon-map.mjs\`. web/test/icon-vocabulary.test.ts
// fails when this file is stale.

import {
${exports.map((e) => `  ${e},`).join("\n")}
} from "@shared/ui/foundations/icons"

import type * as React from "react"

export const ICON_MAP: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
${exports.map((e) => `  ${e},`).join("\n")}
}
`

if (CHECK) {
  const current = (() => {
    try {
      return read(OUT)
    } catch {
      return ""
    }
  })()
  if (current !== body) {
    console.error(`icon-map: STALE — run \`node scripts/icon-map.mjs\` (${exports.length} glyphs wanted)`)
    process.exit(1)
  }
  console.log(`icon-map: OK, ${exports.length} glyphs, current.`)
} else {
  writeFileSync(OUT, body)
  console.log(`icon-map: wrote ${exports.length} glyphs (of ${drawn.size} the kit draws)`)
}
